name: Dataiku GitOps CI

on:
  pull_request:
    branches:
      - prod

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dataiku GitOps Action
        uses: qcastel/dataiku-gitops-github-action@master
        with:
          python-script: "tests.py"
          dataiku_api_token: ${{ secrets.DATAIKU_INSTANCE_DEV_CI_API_TOKEN }}
          dataiku_instance_a_url: ${{ vars.DATAIKU_INSTANCE_DEV_URL }}
          dataiku_instance_b_url: ${{ vars.DATAIKU_INSTANCE_STAGING_URL }}
          dataiku_project_key: ${{ vars.DATAIKU_PROJECT_KEY }}
